// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtKCHpDQ-Q0biXlkuNyUidWVBxhU8dzE',
    appId: '1:180169977384:web:404c868ed41e29183ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    authDomain: 'campus-mates-7ee42.firebaseapp.com',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
    measurementId: 'G-LVSZXHYBPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxFmnHUlBHY0yVXi2hB4wTqFdbYeDyjA',
    appId: '1:180169977384:android:29e507f1696066743ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXtKCHpDQ-Q0biXlkuNyUidWVBxhU8dzE',
    appId: '1:180169977384:web:54530d97b361ed623ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    authDomain: 'campus-mates-7ee42.firebaseapp.com',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
    measurementId: 'G-8PKVGG3CBT',
  );

}