// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtKCHpDQ-Q0biXlkuNyUidWVBxhU8dzE',
    appId: '1:180169977384:web:4d706a89c887e2293ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    authDomain: 'campus-mates-7ee42.firebaseapp.com',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
    measurementId: 'G-5CBV0BFEL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxFmnHUlBHY0yVXi2hB4wTqFdbYeDyjA',
    appId: '1:180169977384:android:29e507f1696066743ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_rpKTPGuHkU6Vwaer3kzyQTmS6zZePgw',
    appId: '1:180169977384:ios:f11799a3461394323ecf1d',
    messagingSenderId: '180169977384',
    projectId: 'campus-mates-7ee42',
    storageBucket: 'campus-mates-7ee42.firebasestorage.app',
    iosBundleId: 'com.example.campusMates',
  );

}