// ignore_for_file: unused_import

import 'package:campus_mates/auth_wrapper.dart';
//import 'package:campus_mates/loginPage.dart';
import 'package:flutter/material.dart';


// 1) firebase_core to initialize Firebase
import 'package:firebase_core/firebase_core.dart';
// 2) options generated by flutterfire configure
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // 3) initialize Firebase with generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

// ignore: use_key_in_widget_constructors
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'College Connect',
      home: AuthWrapper(),
      );
  }
}
 